### ISSUE TITLE
Brainnetome Atlas 

### ISSUE THREAD

**Issue by CerebroDisejecutivo** [sidchop/brainconn#16]
Trying to use the Brainnetome as a custom atlas. It seems to work fine except when using brainconn() with view = "ortho" (it works with the other views), and brainconn3d(), as those produce the following error: "Error in conmat[i, ] : subscript out of bounds".

**Comment by sidchop** [comment]
Hi @CerebroDisejecutivo 
Could you upload the Brainnetome custom atlas (as a .txt/.csv) you are using as an attachment here?

**Comment by CerebroDisejecutivo** [comment]
Sure, here it is. It's separated by tabs   
[BNA_r.txt](https://github.com/sidchop/brainconn/files/5962996/BNA_r.txt)

**Comment by sidchop** [comment]
Atlas seems to work fine: 

```
library(brainconn)

#read custom atlas
bna_atlas <- read.table("~/Downloads/BNA_r.txt", header = T)

#check specifications
check_atlas(bna_atlas)

# create a random binary symetric matrix
r <- c <- 246
random_matrix <- matrix(rbinom(r*c,1,0.001),r,c)
random_matrix <- Matrix::forceSymmetric(random_matrix)

#plot ortho 
brainconn(bna_atlas, conmat = random_matrix, view = "ortho")
brainconn(bna_atlas, conmat = random_matrix, view = "top")
brainconn(bna_atlas, conmat = random_matrix, view = "left")
```
outputs:  ![Rplot1](https://user-images.githubusercontent.com/27250072/107600000-80561d00-6c76-11eb-8805-9fba41eec9a4.png)
![Rplot2](https://user-images.githubusercontent.com/27250072/107600054-ada2cb00-6c76-11eb-95b3-4638c78e9fa4.png)
![Rplot3](https://user-images.githubusercontent.com/27250072/107600063-b5fb0600-6c76-11eb-9686-005bc30c080a.png)

brainconn3d also seems  to work with the atlas:
```
brainconn3D(bna_atlas, conmat = random_matrix)
```
output: ![Screen Shot 2021-02-11 at 2 39 02 pm](https://user-images.githubusercontent.com/27250072/107600156-02464600-6c77-11eb-96a7-4cfbfb6a3c9e.png)

Which means that the connectivity/adjacency matrix you are using is the issue. Could you please check that it is a 247 x 246 matrix. You can also upload the matrix here and I can have a look.

**Comment by sidchop** [comment]
Hi @CerebroDisejecutivo  - let me know if you got this working and ill close the issue.
