### ISSUE TITLE
brainconn ignores the 'thr' optional value

### ISSUE THREAD

**Issue by gdemarchi** [sidchop/brainconn#24]
Hi, thanks for the (hopefully :-) ) great tool.
I'm trying to plot coherence adjacency matrices, generated in fieldtrip/MATLAB, and exported as .csv on a custom atlas generated as per [issue #16 ](https://github.com/sidchop/brainconn/issues/16). Sadly it plots all the edges independently of the value of thr (tried setting it to 50%, 90%, 99% of the max).
For instance 
`> brainconn(bna_atlas, conmat = testcoh, view = "front", thr=0.0604)`
(0.0604 being 99% of the max 0.0610, but I tried also with 100%) produces the following figure, still containing the smaller edges of values  0.02 and 0.04, see the legend:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/33806066/164326657-4fefb156-c05d-468b-8403-4aea489f82d1.png">
Any hint? Thanks ...

**Comment by gdemarchi** [comment]
Coloring with 
`brainconn(bna_atlas, conmat = testcoh, view = "front", thr=0.0604,  edge.color.weighted=TRUE)`
makes it a bit more readable but still I'd prune a few edges ... :-)  
<img width="612" alt="image" src="https://user-images.githubusercontent.com/33806066/164328131-9e353748-9675-445e-9450-d3be9b9acef0.png">

**Comment by sidchop** [comment]
Hi - this should now be fixed. Please let me know if you are still having issues after re-installing the package.

**Comment by gdemarchi** [comment]
Works, brilliant!
<img width="528" alt="image" src="https://user-images.githubusercontent.com/33806066/164458265-3e2b3913-d7be-4697-8ff3-289ec6b6e33a.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/33806066/164459150-91085be6-0641-4a6a-b9b4-3558bd01fe4e.png">
I close the issue now, thanks for the prompt fix (deep in the night 😃 ...)
