### ISSUE TITLE
Error message:  "No layout function defined for objects of class <matrix>"

### ISSUE THREAD

**Issue by srinivasbalachander** [sidchop/brainconn#27]
Hello Sid,

Greetings - thanks for your great package!

Everything was working fine till today - I updated my R version (to 4.3.0) and all packages. 

I now keep getting this error message, for all examples/vignettes that you've provided.

> brainconn(atlas ="schaefer300_n7", conmat=example_unweighted_undirected, view="ortho")
Error in `handlers[[1L]]()`:
! No layout function defined for objects of class <matrix>
Run `rlang::last_trace()` to see where the error occurred.

I think there's an issue with create_layout from ggraph, which for some reason takes data.frame objects but not matrices. 

I tried modifying your build_plot function, in the lines with the create_layout function, I added as.data.frame(conmat) - things worked fine after that.

Hope this is helpful!

Best regards,

Srinivas B

**Comment by ntcnv** [comment]
Hello. I followed that strategy too to manage with the same error. But unfortunately I am still figthting to find out a solution. I do not know whether something went wrong during installation, but I can read properly the brainconn library and when  running the example I can see that it returns the first code reported in the tutorial and the error mentioned here in red. Could you please suggest what to do? Thanks
