### ISSUE TITLE
Not able to plot the connectivity 

### ISSUE THREAD

**Issue by vedantkan** [sidchop/brainconn#30]
Hello,

I installed the package yesterday. I am trying to plot the connectivity matrix using a custom atlas, but the plot does not display the correct connection. 

Here is my custom atlas
[custom_atlas.csv](https://github.com/sidchop/brainconn/files/12560214/custom_atlas.csv)
And here is a sample conn matrix I am trying to use 
[sample_exp.csv](https://github.com/sidchop/brainconn/files/12560220/sample_exp.csv)

When I run the code 
brainconn(atlas = custom_atlas, conmat = con_mat, edge.color = "black",
          node.color = "steelblue", labels = TRUE, label.size = 3,
          all.nodes = TRUE)
![image2](https://github.com/sidchop/brainconn/assets/68374993/28795295-0d40-4d17-a088-c759e47e58f3)
I get the following result which shows a connectivity between 2 nodes which aren't even connected. 

Also using any value other than 1 for weights gives me the following error 
"Error in `$<-.data.frame`(`*tmp*`, "x", value = c(-32L, 32L, 0L, -35L,  : 
  replacement has 19 rows, data has 1"

Even when trying to plot the same example provided on the README page, it gives me different results compared to the plot shown in the image. Here is what I get. 
![image](https://github.com/sidchop/brainconn/assets/68374993/98e5d331-3ae3-401f-98c2-8010cad280fc)

I am using the package for the first time, so I am not sure what am I doing wring. Any help would be appreciated.

Thank you.

**Comment by sidchop** [comment]
Looks like the last pr broke some things. I have undone this and the package should work fine now. Please try reinstalling and let me know if you have any other issues.

**Comment by vedantkan** [comment]
I did reinstall the package and it works fine now. Thank you for you help!
